version: '3'

services:
  # 后端服务
  backend:
    build:
      context: ./RobotTurtles-master
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./RobotTurtles-master/improved_model:/app/improved_model
    restart: always
    environment:
      - FLASK_APP=robot-turtles-server/server.py
      - FLASK_ENV=development
      - MODEL_PATH=/app/improved_model/improved_model.pt
      - PYTHONUNBUFFERED=1
    networks:
      - robot-turtles-network

  # 前端服务
  frontend:
    build:
      context: ./robot-turtles-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    restart: always
    networks:
      - robot-turtles-network

networks:
  robot-turtles-network:
    driver: bridge 