# 训练配置
training:
  num_epochs: 10
  steps_per_epoch: 512
  batch_size: 32
  num_processes: 2
  eval_interval: 2
  checkpoint_dir: "outputs/checkpoints"
  tensorboard_dir: "outputs/tensorboard"
  learning_rate: 3e-4

# PPO算法配置
ppo:
  gamma: 0.99
  epsilon: 0.2
  value_coef: 0.5
  entropy_coef: 0.01
  num_updates: 5
  lambda_: 0.95

# 游戏环境配置
environment:
  num_players: 2
  enable_bug_card: true
  three_rounds: false
  max_program_size: 20

# 模型配置
model:
  input_channels: 9

# 基础配置
device: cuda
seed: 42 